# Site
name: 'WakeHustle'
title: 'Wake, hustle and win.'
description: 'Wake, hustle and win.'
logo: 'assets/images/logo.png' 
logogrey: 'assets/images/logo_grey.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'wakehustle@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'



include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-admin
  - jekyll-seo-tag


authors:
    sal:
      name:           Piyush Varshney
      site:           https://piyushvarshney.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Piyush, the author of WakeHustle, the site you're currently playing around. I hope you like it!"
      email:          piyush@wakehustle.com
      instagram:        https://instagram.com/piyushvrshney



# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Piyush
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
